# This is a basic workflow to help you get started with Actions

name: check_run

# Controls when the workflow will run
on:
  check_run:
    types: [completed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: echo 
        run: echo "check_run completed"
          
      # Runs a dump-github-event-client_payload command using the runners shell
      - name: dump github-event-client_payload
        run: |
          echo "${{ github.event }}"
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/docs
          event-type: dispatch-from-oc.template
          client-payload: '{  "repository": "${{ github.repository }}", "run_id": "${{ github.run_id }}",  "artifact": "template.md" }'

          
          
          
