
name: Sample


on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
  
env:
  VERSIONS: "[ \"9.0.0\", \"11.0.0\" ]" 

jobs:
  prepare-matrix:
    name: Prepare Matrix Output
    runs-on: ubuntu-latest
    outputs: 
      all_versions: ${{ steps.step1.outputs.matrix }}
    steps: 
      - name: Create Matrix Variable
        id: step1
        run: echo "matrix=${{env.VERSIONS}}" >> $GITHUB_OUTPUT

  deploy-gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    strategy: 
      matrix: 
        version: ${{ fromJSON(needs.prepare-matrix.outputs.all_versions) }}
    steps:
      - run: echo ${{ matrix }}
      - run: echo ${{ matrix.version }}
