
name: Sample


on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  matrix-prep-bazelversion:
    # Prepares the 'bazelversion' axis of the test matrix
    runs-on: ubuntu-latest
    steps:
      # Need the repo checked out in order to read the file
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "18.x"
        
      - name: generate minimal 
        run: |
          ls -la
          ls -la rules
          ls -la rules/json2str.js
          cat rules/minimal.json
          node rules/json2str.js rules/minimal.json
        
    outputs:
      # Will look like '["6.0.0rc1", "5.3.2"]'
      bazelversions: ${{ toJSON(steps.*.outputs) }}
      
  test:
    runs-on: ubuntu-latest
    needs:
      - matrix-prep-bazelversion

    strategy:
      matrix:
        # Reads the value saved by "outputs" of the jobs above
        bazelversion: ${{ fromJSON(needs.matrix-prep-bazelversion.outputs.bazelversions) }}
    steps:
      - run: echo ${{ matrix.bazelversion }}
